# $NetBSD$

DISTNAME=	rebound-3.24.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	${MASTER_SITE_PYPI:=r/rebound/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/hannorein/rebound
COMMENT=	Open-source multi-purpose N-body code
LICENSE=	gnu-gpl-v3

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
