# $NetBSD$

DISTNAME=	imageio_ffmpeg-0.6.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=	multimedia python
MASTER_SITES=	${MASTER_SITE_PYPI:=i/imageio_ffmpeg/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/imageio/imageio-ffmpeg
COMMENT=	FFMPEG wrapper for Python
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
