# $NetBSD$

DISTNAME=	tk_html_widgets-0.4.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_PYPI:=t/tk_html_widgets/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://pypi.org/project/tk_html_widgets/
COMMENT=	HTML widgets for tkinter
LICENSE=	mit

DEPENDS+=	${PYPKGPREFIX}-Pillow>=9.2.0:../../graphics/py-Pillow
#DEPENDS+=	${PYPKGPREFIX}-Tk>=0:../../x11/py-Tk

# url2pkg-marker (please do not remove this line.)
.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
