# $NetBSD$

DISTNAME=	python-json-logger-2.0.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/python-//}
CATEGORIES=	textproc python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/python-json-logger/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/madzak/python-json-logger
COMMENT=	Python library adding a json log formatter
LICENSE=	modified-bsd

PYTHON_VERSIONS_INCOMPATIBLE+=	27

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
