# $NetBSD$

DISTNAME=	celerity-0.35.0
CATEGORIES=	python math
MASTER_SITES=	${MASTER_SITE_PYPI:=c/celerity/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://pypi.org/project/celerity/
COMMENT=	lightweight zero-dependency and type-safe library for astronomy
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
