# $NetBSD$

DISTNAME=	jupyter_packaging-0.12.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	pkgsrc_myownpkgs
MASTER_SITES=	${MASTER_SITE_PYPI:=j/jupyter_packaging/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://pypi.org/project/jupyter_packaging/
COMMENT=	Tools to help build and install Jupyter Python packages
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
