# $NetBSD$

DISTNAME=	fontawesome5
PKGNAME=	tex-${DISTNAME}-5.15.4
TEXLIVE_REV=	63207
CATEGORIES=	fonts
MASTER_SITES=	${MASTER_SITE_TEX_CTAN:=systems/texlive/tlnet/archive/}
EXTRACT_SUFX=	.tar.xz

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.dnsbalance.ring.gr.jp/pub/text/CTAN/systems/texlive/tlnet/archive/
COMMENT=	awesome5 font
LICENSE=	lppl-1.3c

WRKSRC=		${WRKDIR} # TODO: one of fonts tex tlpkg, or leave it as-is
USE_LANGUAGES=	# none

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
