# $NetBSD$

DISTNAME=	astropy_iers_data-0.2024.6.10.0.30.47
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/_iers_/-iers-/}
CATEGORIES=	math python
MASTER_SITES=	${MASTER_SITE_PYPI:=a/astropy-iers-data/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://pypi.org/project/astropy-iers-data/
COMMENT=	IERS Earth Rotation and Leap Second tables for Astropy
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
