# $NetBSD$

DISTNAME=	yatex1.83
PKGNAME=	${DISTNAME:S/yatex/yatex-/}
CATEGORIES=	devel
MASTER_SITES=	https://www.yatex.org/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.yatex.org/
COMMENT=	Yet Another TeX mode for Emacs
LICENSE=	yatex

USE_LANGUAGES=	# none

MAKE_FILE=	makefile
NO_BUILD=	yes
INSTALL_TARGET=	install-real

.include "../../mk/bsd.pkg.mk"
