# $NetBSD$

DISTNAME=	oorb-1.3.0
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_GITHUB:=oorb/}
GITHUB_PROJECT=	oorb
GITHUB_TAG=	refs/tags/v${PKGVERSION_NOREV}

DISTFILES+=	${DISTNAME}${EXTRACT_SUFX}
DISTFILES+=	header.430_229
SITES.header.430_229=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp1550.430
SITES.ascp1550.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp1650.430
SITES.ascp1650.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp1750.430
SITES.ascp1750.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp1850.430
SITES.ascp1850.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp1950.430
SITES.ascp1950.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp2050.430
SITES.ascp2050.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp2150.430
SITES.ascp2150.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp2250.430
SITES.ascp2250.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp2350.430
SITES.ascp2350.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp2450.430
SITES.ascp2450.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	ascp2550.430
SITES.ascp2550.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	testpo.430
SITES.testpo.430=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de430/
DISTFILES+=	header.431_229
SITES.header.431_229=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm13000.431
SITES.ascm13000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm12000.431
SITES.ascm12000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm11000.431
SITES.ascm11000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm10000.431
SITES.ascm10000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm09000.431
SITES.ascm09000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm08000.431
SITES.ascm08000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm07000.431
SITES.ascm07000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm06000.431
SITES.ascm06000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm05000.431
SITES.ascm05000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm04000.431
SITES.ascm04000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm03000.431
SITES.ascm03000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm02000.431
SITES.ascm02000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascm01000.431
SITES.ascm01000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp00000.431
SITES.ascp00000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp01000.431
SITES.ascp01000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp02000.431
SITES.ascp02000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp03000.431
SITES.ascp03000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp04000.431
SITES.ascp04000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp05000.431
SITES.ascp05000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp06000.431
SITES.ascp06000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp07000.431
SITES.ascp07000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp08000.431
SITES.ascp08000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp09000.431
SITES.ascp09000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp10000.431
SITES.ascp10000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp11000.431
SITES.ascp11000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp12000.431
SITES.ascp12000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp13000.431
SITES.ascp13000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp14000.431
SITES.ascp14000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp15000.431
SITES.ascp15000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	ascp16000.431
SITES.ascp16000.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	testpo.431
SITES.testpo.431=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/
DISTFILES+=	header.440
SITES.header.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp01550.440
SITES.ascp01550.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp01650.440
SITES.ascp01650.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp01750.440
SITES.ascp01750.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp01850.440
SITES.ascp01850.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp01950.440
SITES.ascp01950.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp02050.440
SITES.ascp02050.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp02150.440
SITES.ascp02150.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp02250.440
SITES.ascp02250.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp02350.440
SITES.ascp02350.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp02450.440
SITES.ascp02450.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	ascp02550.440
SITES.ascp02550.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	testpo.440
SITES.testpo.440=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de440/
DISTFILES+=	header.441
SITES.header.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm13000.441
SITES.ascm13000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm12000.441
SITES.ascm12000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm11000.441
SITES.ascm11000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm10000.441
SITES.ascm10000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm09000.441
SITES.ascm09000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm08000.441
SITES.ascm08000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm07000.441
SITES.ascm07000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm06000.441
SITES.ascm06000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm05000.441
SITES.ascm05000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm04000.441
SITES.ascm04000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm03000.441
SITES.ascm03000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm02000.441
SITES.ascm02000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascm01000.441
SITES.ascm01000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp00000.441
SITES.ascp00000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp01000.441
SITES.ascp01000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp02000.441
SITES.ascp02000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp03000.441
SITES.ascp03000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp04000.441
SITES.ascp04000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp05000.441
SITES.ascp05000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp06000.441
SITES.ascp06000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp07000.441
SITES.ascp07000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp08000.441
SITES.ascp08000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp09000.441
SITES.ascp09000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp10000.441
SITES.ascp10000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp11000.441
SITES.ascp11000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp12000.441
SITES.ascp12000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp13000.441
SITES.ascp13000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp14000.441
SITES.ascp14000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp15000.441
SITES.ascp15000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	ascp16000.441
SITES.ascp16000.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/
DISTFILES+=	testpo.441
SITES.testpo.441=	ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/oorb/oorb/
COMMENT=	Open-source orbit-computation package for Solar System objects
LICENSE=	gpl-3.0

WRKSRC=	${WRKDIR}/${DISTNAME}

USE_LANGUAGES+=	fortran

DEPENDS+=	bash>=0:../../shells/bash
DEPENDS+=	curl>=0:../../www/curl
DEPENDS+=	gcc12>=0:../../lang/gcc12
DEPENDS+=	ghostscript-agpl>=0:../../print/ghostscript-agpl
DEPENDS+=	gmake>=0:../../devel/gmake
DEPENDS+=	gnuplot>=0:../../graphics/gnuplot
DEPENDS+=	dvipsk>=0:../../print/dvipsk
DEPENDS+=	tex-ae>=0:../../fonts/tex-ae
DEPENDS+=	tex-acronym>=0:../../print/tex-acronym
DEPENDS+=	tex-bigfoot>=0:../../print/tex-bigfoot
DEPENDS+=	wget>=0:../../net/wget

do-configure:
	(cd ${WRKSRC}; \
	bash ./configure gfortran opt;)

pre-build:
	(cd ${WRKSRC}/doc; \
	latex OpenOrb_Tutorial.tex; \
	latex OpenOrb_Tutorial.tex; \
	dvips OpenOrb_Tutorial.dvi; \
	ps2pdfwr OpenOrb_Tutorial.ps;)

do-build:
	(cd ${WRKSRC}/build; \
	gmake;)

post-build:
	(cd ${WRKSRC}/data/JPL_ephemeris; \
	gmake clean; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/header.430_229 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp1550.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp1650.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp1750.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp1850.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp1950.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp2050.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp2150.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp2250.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp2350.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp2450.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp2550.430 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/testpo.430 .; \
	gmake asc2eph; \
	gmake ascii.430; \
	gmake de430.dat; \
	gmake ephtester; \
	gmake test; \
	gmake eph;)
	(cd ${WRKSRC}/data/JPL_ephemeris; \
	gmake EPH_TYPE=431 clean; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/header.431_229 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm13000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm12000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm11000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm10000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm09000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm08000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm07000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm06000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm05000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm04000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm03000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm02000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm01000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp00000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp01000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp03000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp04000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp05000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp06000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp07000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp08000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp09000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp10000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp11000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp12000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp13000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp14000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp15000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp16000.431 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/testpo.431 .; \
	gmake EPH_TYPE=431 asc2eph; \
	gmake EPH_TYPE=431 ascii.431; \
	gmake EPH_TYPE=431 de431.dat; \
	gmake EPH_TYPE=431 ephtester; \
	gmake EPH_TYPE=431 test; \
	gmake EPH_TYPE=431 eph;)
	(cd ${WRKSRC}/data/JPL_ephemeris; \
	gmake EPH_TYPE=440 clean; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/header.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp01550.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp01650.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp01750.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp01850.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp01950.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02050.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02150.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02250.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02350.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02450.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02550.440 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/testpo.440 .; \
	gmake EPH_TYPE=440 asc2eph; \
	gmake EPH_TYPE=440 ascii.440; \
	gmake EPH_TYPE=440 de440.dat; \
	gmake EPH_TYPE=440 ephtester; \
	gmake EPH_TYPE=440 test; \
	gmake EPH_TYPE=440 eph;)
	(cd ${WRKSRC}/data/JPL_ephemeris; \
	gmake EPH_TYPE=441 clean; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/header.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm13000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm12000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm11000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm10000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm09000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm08000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm07000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm06000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm05000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm04000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm03000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm02000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascm01000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp00000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp01000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp02000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp03000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp04000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp05000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp06000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp07000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp08000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp09000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp10000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp11000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp12000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp13000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp14000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp15000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/ascp16000.441 .; \
        ${CP} -pf ${PKGSRCDIR}/distfiles/testpo.441 .; \
	gmake EPH_TYPE=441 asc2eph; \
	gmake EPH_TYPE=441 ascii.441; \
	gmake EPH_TYPE=441 de441.dat; \
	gmake EPH_TYPE=441 ephtester; \
	gmake EPH_TYPE=441 test; \
	gmake EPH_TYPE=441 eph;)
	
pre-install:
	mkdir -p ${DESTDIR}${PREFIX}/bin; \
	mkdir -p ${DESTDIR}${PREFIX}/etc/oorb; \
	mkdir -p ${DESTDIR}${PREFIX}/lib; \
	mkdir -p ${DESTDIR}${PREFIX}/share/oorb; \
	mkdir -p ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \

do-install:
	${CP} ${WRKSRC}/bin/ephemeris_linking ${DESTDIR}${PREFIX}/bin; \
	${CP} ${WRKSRC}/bin/oorb ${DESTDIR}${PREFIX}/bin; \
	${CP} ${WRKSRC}/bin/orbit_linking ${DESTDIR}${PREFIX}/bin; \
	${CP} ${WRKSRC}/data/ET-UT.dat ${DESTDIR}${PREFIX}/share/oorb; \
	${CP} ${WRKSRC}/data/OBSCODE.dat ${DESTDIR}${PREFIX}/share/oorb; \
	${CP} ${WRKSRC}/data/TAI-UTC.dat ${DESTDIR}${PREFIX}/share/oorb; \
	${CP} ${WRKSRC}/data/de430.dat ${DESTDIR}${PREFIX}/share/oorb; \
	${CP} ${WRKSRC}/data/de440.dat ${DESTDIR}${PREFIX}/share/oorb; \
	${CP} ${WRKSRC}/data/de441.dat ${DESTDIR}${PREFIX}/share/oorb; \
	${CP} ${WRKSRC}/data/updateOBSCODE ${DESTDIR}${PREFIX}/bin; \
	${CP} ${WRKSRC}/doc/OpenOrb_Tutorial.pdf ${DESTDIR}${PREFIX}/share/oorb; \
	${CP} ${WRKSRC}/lib/liboorb.a ${DESTDIR}${PREFIX}/lib; \
	${CP} ${WRKSRC}/lib/liboorb.so ${DESTDIR}${PREFIX}/lib; \
	${CP} ${WRKSRC}/main/oorb.conf ${DESTDIR}${PREFIX}/etc/oorb; \
	${CP} ${WRKSRC}/gnuplot/cos_plot_car.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/cos_plot_kep.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/ls_plot.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/sor_plot_car.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/sor_plot_kep.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/sor_plot_kep_nolog.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/sor_plot_range.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/vomcmc_plot_car.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/vomcmc_plot_kep.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/vov_plot_car.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \
	${CP} ${WRKSRC}/gnuplot/vov_plot_kep.gp ${DESTDIR}${PREFIX}/share/oorb/gnuplot; \

# url2pkg-marker (please do not remove this line.)
.include "../../math/lapack/buildlink3.mk"
.include "../../lang/gcc12/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
