$NetBSD$

--- pyproject.toml.orig	2025-06-21 00:46:58.091153852 +0000
+++ pyproject.toml
@@ -13,7 +13,7 @@ dependencies = [
     "asdf_wcs_schemas >= 0.5.0",
     "asdf-astropy >= 0.8.0",
 ]
-license-files = ["licenses/LICENSE.rst"]
+license = { file = "licenses/LICENSE.rst" }
 dynamic = [
     "version",
 ]
