# $NetBSD$

DISTNAME=	skyfield-1.51
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	${MASTER_SITE_PYPI:=s/skyfield/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://pypi.org/project/skyfield/
COMMENT=	Pure-Python astronomy package for positions of planets
LICENSE=	mit

# url2pkg-marker (please do not remove this line.)
.include "../../lang/python/egg.mk"
.include "../../math/py-numpy/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
