# $NetBSD$

DISTNAME=	# empty
PKGNAME=	meta-all-1.0
PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	https://github.com/kinoshitadaisuke/pkgsrc_myownpkgs
DISTFILES=	# empty

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kinoshitadaisuke/pkgsrc_myownpkgs
COMMENT=	Meta packages
LICENSE=	modified-bsd

META_PACKAGE=	yes

.include "../../mk/bsd.prefs.mk"

DEPENDS+=	meta-astronomy>=0:../../pkgsrc_myownpkgs/meta-astronomy
DEPENDS+=	meta-basictools>=0:../../pkgsrc_myownpkgs/meta-basictools
DEPENDS+=	meta-benchmarks>=0:../../pkgsrc_myownpkgs/meta-benchmarks
DEPENDS+=	meta-fonts>=0:../../pkgsrc_myownpkgs/meta-fonts
DEPENDS+=	meta-geography>=0:../../pkgsrc_myownpkgs/meta-geography
DEPENDS+=	meta-graphics>=0:../../pkgsrc_myownpkgs/meta-graphics
DEPENDS+=	meta-japanese>=0:../../pkgsrc_myownpkgs/meta-japanese
DEPENDS+=	meta-lang>=0:../../pkgsrc_myownpkgs/meta-lang
DEPENDS+=	meta-latex>=0:../../pkgsrc_myownpkgs/meta-latex
DEPENDS+=	meta-net>=0:../../pkgsrc_myownpkgs/meta-net
DEPENDS+=	meta-nvmm>=0:../../pkgsrc_myownpkgs/meta-nvmm
DEPENDS+=	meta-openstax>=0:../../pkgsrc_myownpkgs/meta-openstax
DEPENDS+=	meta-python>=0:../../pkgsrc_myownpkgs/meta-python
DEPENDS+=	meta-raspberrypi>=0:../../pkgsrc_myownpkgs/meta-raspberrypi
DEPENDS+=	meta-science>=0:../../pkgsrc_myownpkgs/meta-science
DEPENDS+=	meta-video>=0:../../pkgsrc_myownpkgs/meta-video
DEPENDS+=	meta-vpn>=0:../../pkgsrc_myownpkgs/meta-vpn
DEPENDS+=	meta-webbrowsers>=0:../../pkgsrc_myownpkgs/meta-webbrowsers
DEPENDS+=	meta-www>=0:../../pkgsrc_myownpkgs/meta-www
DEPENDS+=	meta-x11>=0:../../pkgsrc_myownpkgs/meta-x11

.include "../../lang/python/wheel.mk"
.include "../../mk/bsd.pkg.mk"
