# $NetBSD$

PKGNAME=	cyberbit-ttf-3.0
FONT_FILE=	Cyberbit.ZIP

COMMENT=	Multilingual TrueType font from Bitstream

CONFLICTS=	cyberbase-ttf-[0-9]*

NO_CONFIGURE=	yes
NO_BUILD=	yes

.include "./Makefile.common"
.include "../../mk/bsd.pkg.mk"
