$NetBSD$

--- pyproject.toml.orig	2025-06-21 05:40:55.000000000 +0000
+++ pyproject.toml
@@ -20,8 +20,7 @@ classifiers = [
     "Programming Language :: Python :: 3.11",
     "Topic :: Documentation :: Sphinx",
 ]
-license = "MIT"
-license-files = ["LICENSE"]
+license = { text = "MIT" }
 readme = "README.rst"
 dependencies = [
     "requests>=2.28.1",
