$NetBSD$

--- pyproject.toml.orig	2025-05-20 13:21:57.000000000 +0000
+++ pyproject.toml
@@ -8,8 +8,8 @@ readme = "README.rst"
 authors = [
     { name = "The Astropy Developers", email = "astropy.team@gmail.com" }
 ]
-license = "BSD-3-Clause"
-license-files = ["LICENSE.rst", "licenses/*.rst"]
+license = { text = "BSD-3-Clause" }
+#license-files = ["LICENSE.rst", "licenses/*.rst"]
 requires-python = ">=3.11"
 classifiers = [
     "Intended Audience :: Science/Research",
